// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmyajxekgerixzojzlej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteWFqeGVrZ2VyaXh6b2p6bGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzAyMzYsImV4cCI6MjA2NTM0NjIzNn0.182BcAnKDY01jUNAANUl2ik4u0UnEe3fPegI9lpN6a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);